# Dependencies
markdown:         rdiscount
highlighter:      pygments

# Permalinks
permalink:        pretty

# Server
destination:      ./_gh_pages
exclude:          [".gitignore", "Gruntfile.js", "package.json", "node_modules", "README.md", "server_architecture.png", "wiki.py"]
port:             9000

# Custom vars
repo:             https://github.com/EiffelWebFramework/EWF
download:         https://github.com/EiffelWebFramework/EWF/archive/v0.4.0.zip
